image: gitpod/workspace-full-vnc:latest

tasks: 
  - name: Submodule update
    init: git submodule update --remote --merge
    command: exit

  - name: Submodules
    init: git submodule update --init --recursive
    command: exit

  - name: Jekyll blog
    before: cd blogs/mainjekyll && gem install jekyll bundle
    init: cd ~ && cd /workspace/ultimate-gitpod-set/blogs/mainjekyll && bundle install
    command: |
        cd ~ && cd /workspace/ultimate-gitpod-set/blogs/mainjekyll && bundle install && bundle exec jekyll serve

  - name: CODEDOC blog
    before: cd ~ && cd /workspace/ultimate-gitpod-set/blogs/codedoc && npm i -g @codedoc/cli
    init: cd ~ && cd /workspace/ultimate-gitpod-set/blogs/codedoc && codedoc install
    command: cd ~ && cd /workspace/ultimate-gitpod-set/blogs/codedoc && codedoc s

  - name: Extra Terminal
    init: bash
    command: sudo apt install neofetch && neofetch